### ISSUE TITLE
TPD uses internal APIs in PDE that are no longer present in Photon

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-cbi/targetplatform-dsl#76] opened 2018-04-20 12:59 UTC
I just tried using TPD with Photon M6 and got this error while doing "Set as Target Platform"

```
An internal error occurred during: "Setting target platform definition file".

java.lang.NoSuchMethodError: org.eclipse.pde.internal.core.PDECore.acquireService(Ljava/lang/String;)Ljava/lang/Object;
	at fr.obeo.releng.targetplatform.ui.handler.PDEIntegration.<init>(PDEIntegration.java:42)
	at fr.obeo.releng.targetplatform.ui.handler.ConvertTargetPlatformJob.run(ConvertTargetPlatformJob.java:85)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Comment by jonahkichwacoders** [comment] 2018-04-20 13:02
The change in Eclipse that TPD needs to adapt to is https://bugs.eclipse.org/bugs/show_bug.cgi?id=527685 -- specifically https://git.eclipse.org/r/#/c/112233/2/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/PDECore.java

**Comment by jonahkichwacoders** [comment] 2018-04-20 13:04
The call is from here: https://github.com/mbarbero/fr.obeo.releng.targetplatform/blob/6496514581584fb215942808254d49a82a3a5baf/fr.obeo.releng.targetplatform.ui/src/fr/obeo/releng/targetplatform/ui/handler/PDEIntegration.java#L42

**Comment by jonahkichwacoders** [comment] 2018-04-20 13:05
The workaround is to do generation in two steps, 1st do "Create Target Definition File" and then manually set the target file.

**Comment by JonasHelming** [comment] 2018-07-11 10:58
https://github.com/mbarbero/fr.obeo.releng.targetplatform/pull/80

**Comment by JonasHelming** [comment] 2018-07-12 13:32
https://github.com/mbarbero/fr.obeo.releng.targetplatform/pull/81

**Comment by JonasHelming** [comment] 2018-07-31 08:49
@mbarbero : Any chance to merge this? This is really a blocker...

**Comment by branflake2267** [comment] 2018-08-12 22:50
What's the status?

**Comment by mbarbero** [comment] 2018-08-30 13:02
This repo is in the process of being moved to the Eclipse CBI project. I'm hoping everything will be kept as is and that redirections will be set up. As soon as it's done, I'll fix this issue and release a new version. Add yourself to the cc list of this bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=538414 if you want to track the move.

Thanks for your patience.

**Comment by JonasHelming** [comment] 2018-09-05 11:56
I can see that the PR was merged. where can we find an update site containing the fix?

**Comment by mbarbero** [comment] 2018-09-05 11:59
Unfortunately, the PR has been closed due to transfer to Eclipse CBI (history needed to be squashed). I'll retrofit the change into the new repo.

If you want to see your PR in the context of "old" history, check on https://wiki.eclipse.org/GitHub#End_User_required_actions

**Comment by mbarbero** [comment] 2018-09-05 21:10
Thanks for your report and contribution.

SNAPSHOT update site is available at http://download.eclipse.org/cbi/tpd/3.0.0-SNAPSHOT/

**Comment by jfaltermeier** [comment] 2018-09-11 06:46
I tested the Snapshot build and it looks good. Thanks!

**Comment by miklossy** [comment] 2020-04-27 15:56
@mbarbero I tested this and think that the issue is fixed and can be closed.

**Comment by mbarbero** [comment] 2020-04-27 15:57
Thanks. closing.

**Closed by mbarbero** 2020-04-27 15:57 UTC
