### ISSUE TITLE
Source format for comments

### ISSUE THREAD

**Issue by Pontesegger** [eclipse-cbi/targetplatform-dsl#48] opened 2014-11-03 13:22 UTC
Source formatting for comments within locations does not indent the first comment if it is located before any item

eg

location ... {
//some comment
    org.eclipse....
}

trivial, but looks ugly :)

**Comment by mbarbero** [comment] 2015-10-30 08:54
It seems that the new formatter API is available (but provisional https://eclipse.org/Xtext/documentation/303_runtime_concepts.html#formatting). I will try to play with it.

**Comment by miklossy** [comment] 2020-04-22 18:04
@mbarbero @mduft : It is the default behavior of Xtext, and it is considered as a feature and not a bug.
See [comment](https://github.com/eclipse/xtext-core/issues/415#issuecomment-334724237). However, using the Xtext Formatting2 API, it is possible to override this default behavior and provide a customized one. I created a [PR](https://github.com/eclipse-cbi/targetplatform-dsl/pull/100) that also includes the suggested customization.

**Comment by mbarbero** [comment] 2020-04-27 08:48
Fixed via PR #100

**Closed by mbarbero** 2020-04-27 08:48 UTC
Labels: bug, depends on Xtext
